Problem: 0.7.x fix-unlucky-tx command does not include concurrency and null indexer
crypto-org-chain/cronos pull request #543
Opened 2022-06-08 07:23 UTC by allthatjazzleo

fix #542 

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest master? 
- [ ] Have you checked your code compiles? (`make`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`make test`)
- [ ] Have you checked your code formatting is correct? (`go fmt`)
- [ ] Have you checked your basic code style is fine? (`golangci-lint run`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`go list -json -m all | nancy sleuth`)
- [ ] If your changes affect the client infrastructure, have you run the integration test?
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-org-chain/chain-main/blob/master/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-org-chain/chain-main/blob/master/CONTRIBUTING.md#developer-certificate-of-originn).

Thank you for your code, it's appreciated! :)

2022-06-08 08:18 UTC, yihuang requested changes
we can also change the `cobra.ExactArgs(1)` -> `cobra.ExactArgs(0)` now.

2022-06-08 08:37 UTC, allthatjazzleo commented on cmd/cronosd/cmd/fix-unlucky-tx.go
> +							fmt.Println(height, txIndex)
do you mean move 
```
						if printBlockNumbers {
							fmt.Println(height)
							return nil
						}
```
before 
```
txIndex++
```
?

2022-06-08 08:38 UTC, allthatjazzleo commented on cmd/cronosd/cmd/fix-unlucky-tx.go
> +							fmt.Println(height)
do you mean move 
```
						if printBlockNumbers {
							fmt.Println(height)
							return nil
						}
```
before 
```
txIndex++
```
?

2022-06-09 05:33 UTC, yihuang commented on cmd/cronosd/cmd/fix-unlucky-tx.go
> +							 // ignore non-eth tx
```suggestion
							// ignore non-eth tx
```

2022-06-09 06:33 UTC, merged